import type { Metadata } from "next";
import "@/app/ui/global.css";
import { Roboto } from "next/font/google"; // Add Roboto font
import Header from "@/app/ui/Header";
import { userData } from "./lib/data";

const roboto = Roboto({
  // Initialize Roboto font
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await userData.getUser();
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased px-20 relative`}>
        {user?.error && <p className="text-red-500">Error: {user.error}</p>}
        {user && <Header firstName={user.settings?.first_name} />}
        {children}
      </body>
    </html>
  );
}
