import type { Metadata } from "next";
import "@/app/ui/global.css";
import { Roboto } from "next/font/google"; // Add Roboto font
import Header from "@/app/ui/Header";

const roboto = Roboto({
  // Initialize Roboto font
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased px-20 relative`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
